tool:
  # itemNameはMinecraft:hogehogeではなく下記のURLに記載されている「Enum Constant Summary」の物を利用してください。
  # デフォルトは「ARROW」です。idの数値も利用できますが非推奨です。
  # https://jd.bukkit.org/org/bukkit/Material.html (1.7.10)
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (1.8以降)
  itemName: ARROW

  # ホイールでのバイオーム切り替えのディレイ時間をミリ秒(1/1000秒)単位で設定します。(最大で1秒)
  # 1以上の数値が設定されている場合、設定した時間が経過するまで次のバイオームに切り替わらなくなります。
  # 0以下、もしくはコメントアウト等のデフォルト設定にした場合はディレイ時間がなくなります。
  # ※ ディレイ時間を設定した場合、高速でホイール操作を行うと稀に逆順でバイオームが変化する事があります。
  wheelBiomeChangeDelay: 200

  # 各バイオーム操作の最大距離を5～1000ブロックの範囲で設定できます。
  # この距離を長く設定した場合、空中右クリックを行おうとして遠方のバイオームを書き換える場合があるのでご注意ください。
  # デフォルトは5ブロックです。
  range: 5

biomes:
  # useCustomFileをtrueにするとバイオーム情報をファイルから取得します。
  # Cauldronサーバ等でバイオーム情報を取得できない場合はfalseにしていてもファイルからの取得を行います。
  useCustomFile: false
  # バイオーム情報の読み込み元ファイルを指定します。
  biomesFile: biomes.yml
