name: "BiomePainter"
version: "${project.version}-${BUILD_NUMBER}"
author: sasrai
main: jp.sasrai.biomepainter.BiomePainter

softdepend: [ Permissions, PermissionEx ]

commands:
  bpaint:
    description: BiomePainter tool control
    usage: |
      /<command> give - get  tool item.
      /<command> set <biome_name> - set biome directly for tool item.
      /<command> set <biome id> - set biome directly for tool item.

permissions:
  biomepainter.*:
    description: Gives access to all biome edit functions
    children:
      biomepainter.give: true
      biomepainter.list: true
      biomepainter.tool.check: true
      biomepainter.tool.pickup: true
      biomepainter.tool.paint: true
  biomepainter.tool.*:
    children:
      biomepainter.give: true
      biomepainter.list: true
      biomepainter.tool.check: true
      biomepainter.tool.pickup: true
      biomepainter.tool.paint: true
  biomepainter.give:
    description: give
    default: op
  biomepainter.list:
    description: show biome list.
    default: true
  biomepainter.tool.check:
    description: check
    default: true
  biomepainter.tool.pickup:
    description: pickup
    default: true
  biomepainter.tool.paint:
    description: paint
    default: op
